name = "NanoDates"
uuid = "46f1a544-deae-4307-8689-c12aa3c955c6"
keywords = ["Julia", "Dates", "time", "date", "nanoseconds"]
license = "MIT"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
description = "NanoDate is a nanosecond resolved DateTime type"
repo = "https://github.com/JuliaTime/NanoDates.jl.git"
version = "0.3.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[compat]
Aqua = "0.5, 0.6, 0.7, 0.8"
Documenter = "1"
DocumenterTools = "0.1, 0.2, 0.3"
LiveServer = "1"
Parsers = "2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8"
julia = "1.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Dates"]
